#include "static_lang.h"

#define MAX_LANG 2
#define MAX_RECORDS 1024

typedef struct _LANG_MSG_BOX{
    const char * msg_name;
    int msg_id;
}LANG_MSG_BOX;

LANG_MSG_BOX lbox[MAX_LANG][MAX_RECORDS] = { // структура язычных переводов и их индексов

    {
        {"Welcome to test Struct default_list : \n Type help to display tips \n",MSG_CMD_MENU_WELCOME},
        {"Unknown command \n Type help to display tips \n",MSG_CMD_MENU_UNKCMD},
        {"Get count of records  \n Total : %i records in table \n",MSG_CMD_MENU_COFREC},
        {"No arguments ! Try again > \n",MSG_CMD_MENU_NOARG},
        {"Good bye ! \n",MSG_CMD_MENU_BYE},
        {"menu>",MSG_CMD_MENU_MENU},
        {"|   *** VIN ***    |    *** FULL NAME ***    |   *** MODEL ***   |    *** BRAND ***   |\n",MSG_CMD_DISPLAY_HEAD},
        {"No entries! \n",MSG_CMD_DISPLAY_NOENT},
        {"Total items in list : %i\n",MSG_CMD_DISPLAY_TOTAL},
        {"Please write : <Fullname> <Brand> <Model>\n",MSG_CMD_CREATE_HELP},
        {"Input error  you not type <Full Name> ; <Brand> ; <Model>  ; \n",MSG_CMD_CREATE_ERR1},
        {"Input error  you not type <Brand> ; <Model> ; \n",MSG_CMD_CREATE_ERR2},
        {"Input error  you not type <Model> ; \n",MSG_CMD_CREATE_ERR3},
        {"Memory error !\n",MSG_CMD_CREATE_ERRMEM},
        {"Created successful !\n",MSG_CMD_CREATE_OK},
        {"Car [%s] allready exists! \n",MSG_CMD_CREATE_ALLRE},
        {"Please enter new VIN here -> ",MSG_CMD_CON_CREATE_HELP},
        {"Wrong syntax , <VID>\n",MSG_CMD_CON_CREATE_ERR},
        {"The table is empty! \n",MSG_CMD_DELETE_TEMPTY},
        {"VIN %s not found : ( \n",MSG_CMD_DELETE_VNF},
        {"Element is first in the table ! \n",MSG_CMD_DELETE_EFT},
        {"Delete VIN %s SUCCESS! \n",MSG_CMD_DELETE_OK},
        {"Delete VIN %s FAILURE! \n",MSG_CMD_DELETE_ERR2},
        {"DELETE Note . Syntax <VIN> \n",MSG_CMD_DELETE_CON_HELP},
        {"Too much arg in con_delete !",MSG_CMD_DELETE_CON_ERR},
        {"Unknown char or you can't edit VIN \n",MSG_CMD_EDIT_ERR1},
        {"No entries! Nothing to edit\n",MSG_CMD_EDIT_ERR2},
        {"You have not entered the filter after word BY \n",MSG_CMD_EDIT_ERR3},
        {"We edit only current line! \n",MSG_CMD_EDIT_MSG1},
        {"Before Fullname : %s\n",MSG_CMD_EDIT_BF},
        {"After Fullname : %s\n OK! \n",MSG_CMD_EDIT_AF},
        {"Before Brand : %s\n",MSG_CMD_EDIT_BB},
        {"After Brand : %s\n OK! \n",MSG_CMD_EDIT_AB},
        {"Before Model : %s\n",MSG_CMD_EDIT_BM},
        {"After Model : %s\n OK! \n",MSG_CMD_EDIT_AM},
        {"Unknown char or you can't edit VIN \n",MSG_CMD_EDIT_ERR4},
        {"Success!\n",MSG_CMD_EDIT_OK},
        {"<Wrong input> \n ",MSG_CMD_EDIT_CON_ERR},
        {"edit element . Syntax <new data> ; <name of column>  by <column> <data> \n ",MSG_CMD_EDIT_CON_HELP},
        {"File %s not found \n",MSG_CMD_LOAD_FNF},
        {"File open error! \n",MSG_CMD_LOAD_FOE},
        {"\n i_count_bytes : %i \n",MSG_CMD_LOAD_MSG1},
        {"Can't open or create %s file",MSG_CMD_LOAD_ERRIO},
        {"key %s , key %s\n",MSG_CMD_LOAD_MSG2},
        {"\n The password [%s] does not match after decrypt \n",MSG_CMD_LOAD_ERRPASS},
        {"PASSWORD OK!\n",MSG_CMD_LOAD_POK},
        {"PASSWD without encrypt COMPARING [%s] AND [%s]\n",MSG_CMD_LOAD_PWE},
        {"The password [%s] does not match without decrypt, try other method... \n",MSG_CMD_LOAD_PWEERR},
        {"Sorry can't open . Password not matched \n",MSG_CMD_LOAD_PNM},
        {"Error in line not type <Full Name> ; <Brand> ; <Model> ; \n",MSG_CMD_LOAD_ERR1},
        {"Error in line not type <Brand> ; <Model> ; \n",MSG_CMD_LOAD_ERR2},
        {"Error in line not type <Model> ; \n",MSG_CMD_LOAD_ERR3},
        {"Scanning : [%s] [%s] \n",MSG_CMD_LOAD_S},
        {"Load OK! Total : %i lines \n",MSG_CMD_LOAD_OK},
        {"Wrong input <filename> <key>\n",MSG_CMD_LOAD_EIP},
        {"Detect encrypted files! Reading data ... Total %i files \n",MSG_CMD_LOAD_DE},
        {"usage: %s key_file target_file output_file \n",MSG_CMD_LOAD_HELP},
        {"Want to try to enter the password?! Y / N \n",MSG_CMD_LOAD_Q},
        {"Canceling... \n",MSG_CMD_LOAD_CANS},
        {"\nin s_loaded_file . Current key loaded as [%s] \n",MSG_CMD_LOAD_MSG3},
        {"Can't saving \'nothing!\'\n",MSG_CMD_SAVE_ERR},
        {"Saving OK!\n",MSG_CMD_SAVE_OK},
        {"Can't saving \'nothing!\'\n",MSG_CMD_SAVE_ERR1},
        {"%i bytes : \n",MSG_CMD_SAVE_MSG1},
        {"Encrypt and save OK! \n",MSG_CMD_SAVE_EOK},
        {"sz_user_key : %i encrypt : %i \n",MSG_CMD_SAVE_CON_MSG1},
        {"Wrong input <filename> <key> <encrypt> \n",MSG_CMD_SAVE_CON_ERR},
        {"Invalid filename . Allow only A-z and 0-9 first letter \n",MSG_CMD_SAVE_CON_ERR2},
        {"Wrong input \n",MSG_CMD_SEARCH_ERR1},
        {"Not entered value of <type of > <data>\n",MSG_CMD_SEARCH_ERR2},
        {"Not found : ( \n",MSG_CMD_SEARCH_ERR3},
        {"type <name> where <column> <data>\n",MSG_CMD_SEARCH_CON_HELP},
        {"Can't sort one element ! \n",MSG_CMD_SORT_ERR1},
        {"Using method : %i, desc : %i \n",MSG_CMD_SORT_MSG1},
        {"-----------------------BEFORE EDIT-------------------------\n",MSG_CMD_SORT_MSG2},
        {" \n Find previous element: [%s] == MIN : [%s]\n\n",MSG_CMD_SORT_MSG3},
        {"-----NEW TABLE-------%s-------;------ \n",MSG_CMD_SORT_MSG4},
        {"-------------END----------- \n",MSG_CMD_SORT_MSG5},
        {"Sort complete! \n",MSG_CMD_SORT_OK},
        {"Sorting by VIN as default . Err , name not entered \n",MSG_CMD_SORT_HELP},
        {"Sorting by VIN as default . Err , must be \"by\" only \n",MSG_CMD_SORT_HELP1},
        {"Sorting by VIN as default \n",MSG_CMD_SORT_HELP2},
        {"Debugging disabled \n",MSG_CMD_STRUCT_TOOLS_DEBUG},
        {"Debugging enabled \n",MSG_CMD_STRUCT_TOOLS_DEBUGON},
        {"Just removed from memory : %i items!\n",MSG_CMD_STRUCT_TOOLS_DESTRUCT},
        {"Start logging ... %s\n",MSG_CMD_UNIST_STALOG},
        {"Using default Logfile.log \n",MSG_CMD_UNIST_MSG},
        {"ENTER A NEW VIN :",MSG_GUI_CREATE_MSG1},
        {"CANCELED!",MSG_GUI_CREATE_CANS},
        {"ENTER FULLNAME :",MSG_GUI_CREATE_EFN},
        {"ENTER MODEL :",MSG_GUI_CREATE_EM},
        {"ENTER BRAND :",MSG_GUI_CREATE_EB},
        {"YOU ENTERED :",MSG_GUI_CREATE_MSG2},
        {"IT'S OK? PRESS Y(YES)/N(NO) :",MSG_GUI_CREATE_MSG3},
        {"CREATED!",MSG_GUI_CREATE_OK},
        {"CREATE ELEMENT",MSG_GUI_CREATE_MSG4},
        {"WANA EXIT ? PRESS <-",MSG_GUI_CREATE_MSG5},
        {"PRESS ANY KEY TO CONTINUE",MSG_GUI_CREATE_MSG6},
        {"DEBUG is ON ... \n",MSG_GUI_DEBUG_ON},
        {"DEBUG is OFF ... \n",MSG_GUI_DEBUG_OFF},
        {"WANT TO CHANGE FULLNAME ? Y/N ",MSG_GUI_EDIT_EFN},
        {"New FN->",MSG_GUI_EDIT_NFN},
        {"CHANGED to '%s' !",MSG_GUI_EDIT_MSG1},
        {"WANT TO CHANGE MODEL ? Y/N ",MSG_GUI_EDIT_EM},
        {"New M->",MSG_GUI_EDIT_NM},
        {"New B->",MSG_GUI_EDIT_NB},
        {"WANT TO CHANGE BRAND ? Y/N ",MSG_GUI_EDIT_NBB},
        {"EDIT ELEMENT ",MSG_GUI_EDIT_EE},
        {"INFO",MSG_GUI_HELPINFO_MSG1},
        {"HELP",MSG_GUI_HELPINFO_MSG2},
        {"Element deleted successful!",MSG_GUI_LIST_DEL},
        {"CURRENT ELEMENT",MSG_GUI_LISTINFO_MSG1},
        {"Name : %s",MSG_GUI_LISTINFO_NAME},
        {"Surname : %s",MSG_GUI_LISTINFO_SUR},
        {"Middle name : %s",MSG_GUI_LISTINFO_NAME2},
        {"Brand : %s",MSG_GUI_LISTINFO_BRA},
        {"Model : %s",MSG_GUI_LISTINFO_MOD},
        {"LIST",MSG_GUI_LISTINFO_LI},
        {"BROWSER",MSG_GUI_LOAD_MSG1},
        {"LOADED %s OK! PRESS ENTER!",MSG_GUI_LOAD_MSG2},
        {"LOAD METHOD",MSG_GUI_LOAD_MSG3},
        {"SELECTED : '%s'!",MSG_GUI_LOAD_MSG4},
        {"LOAD THIS FILE Y/N ?",MSG_GUI_LOAD_MSG5},
        {"WANT TO ENTER PASSWORD Y/N ?",MSG_GUI_LOAD_MSG6},
        {"ENTER PASSWORD : ",MSG_GUI_LOAD_MSG7},
        {"OK . LOADING...",MSG_GUI_LOAD_MSG8},
        {"ERR LOADING :( PRESS ANY KEY",MSG_GUI_LOAD_MSG9},
        {"SUCCESS! PRESS ANY KEY",MSG_GUI_LOAD_MSG10},
        {"All elements are deleted ! Total %i",MSG_GUI_RESET},
        {"SAVED %s OK! PRESS ENTER!",MSG_GUI_SAVE_MSG1},
        {"CAN'T SAVE NOTHING! PRESS ENTER!",MSG_GUI_SAVE_MSG2},
        {"ENTER NEW FILENAME : ",MSG_GUI_SAVE_MSG3},
        {"Canceled ... PRESS ANY KEY",MSG_GUI_SAVE_MSG4},
        {"FILENAME : ",MSG_GUI_SAVE_MSG5},
        {"%s IS OK ? Y/N ",MSG_GUI_SAVE_MSG6},
        {"SAVED %s OK! PRESS ENTER!",MSG_GUI_SAVE_MSG7},
        {"ENTER NEW FILENAME : ",MSG_GUI_SAVE_MSG8},
        {"ENTER PASSWORD : ",MSG_GUI_SAVE_EP},
        {"SAVING ? Y/N ",MSG_GUI_SAVE_SA},
        {"SAVE METHOD",MSG_GUI_SAVE_SAA},
        {"Saved %s OK!",MSG_GUI_SAVE_MSG9},
        {"SEARCH METHOD",MSG_GUI_SEARCH_PRE},
        {"ENTER %s : ",MSG_GUI_SEARCH_MSG1},
        {"[Beta]Found : [%i]",MSG_GUI_SEARCH_MSG2},
        {"Terminal not supported colors :( \n",MSG_GUI_SETT},
        {"Charcter pressed is = %3d Hopefully it can be printed as '%c'",MSG_SYSMSG_MSG1},
        {"SORT METHOD",MSG_SORT_MSG},
        {"Sort complete!",MSG_SORT_OK},
        {"DEBUG [choice_list=%i] , [i_count_l=%i] Name of VIN = %s ",MSG_GUI_TOOLS_MSG1},
        {"Use arrow keys to go up and down, Press enter to select a choice . F10 to quick EXIT",MSG_GUI_MENU_MSG1},
        {"The panel was hidden!",MSG_GUI_MENU_HID},
        {"The panel was on!",MSG_GUI_MENU_SHOW},
        {"MAIN MENU",MSG_GUI_MENU_MAIN},
        {"No entries!",MSG_GUI_MENU_NOENT},
        {"Use arrow keys to go up and down, Press enter to select a choice . F10 to quick EXIT",MSG_GUI_MENU_MSG2},
        {"You chose choice %d with choice string %s\n",MSG_GUI_MENU_MSG3},
        {"Welcome",MSG_MENU_MSG},
        {"Menu>",MSG_MENU_MSG2},
        {"Not found arg",MSG_MENU_MSG3},
        {"Total : %i",MSG_MENU_MSG4},
        {"Unknown cmd ...",MSG_MENU_MSG5},
        {"Bye !",MSG_MENU_MSG6}






    },

    {
        {"Добро пожаловать в альфа версию структурной базы данных : \n Наберите help для быстрой помощи \n",MSG_CMD_MENU_WELCOME},
        {"Неизвестная команда. \n Введите help для отображения подсказок. \n",MSG_CMD_MENU_UNKCMD},
        {"Получить количество записей в структуре  \n Всего : %i записей в таблице \n",MSG_CMD_MENU_COFREC},
        {"Нет аргументов ! Попробуйте еще раз > \n",MSG_CMD_MENU_NOARG},
        {"Пока ! \n",MSG_CMD_MENU_BYE},
        {"Меню>",MSG_CMD_MENU_MENU},
        {"|   *** VIN ***    |    *** Полное имя  ***  |   *** Модель ***  |   *** Бренд ***    |\n",MSG_CMD_DISPLAY_HEAD},
        {"Нет записей! \n",MSG_CMD_DISPLAY_NOENT},
        {"Всего элементов : %i\n",MSG_CMD_DISPLAY_TOTAL},
        {"Пожалуйста, напишите: <Полное имя> ; <Бренд> ; <Модель> \n",MSG_CMD_CREATE_HELP},
        {"Ошибка ввода,  вы не ввели <Полное имя>; <Бренд>; <Модель>; \n",MSG_CMD_CREATE_ERR1},
        {"Ошибка ввода,  вы не ввели <Бренд>; <Модель>; \n",MSG_CMD_CREATE_ERR2},
        {"Ошибка ввода,  вы не ввели <Модель>; \n",MSG_CMD_CREATE_ERR3},
        {"Ошибка памяти !\n",MSG_CMD_CREATE_ERRMEM},
        {"Создано успешно!\n",MSG_CMD_CREATE_OK},
        {"Автомобиль [%s] уже существует! \n",MSG_CMD_CREATE_ALLRE},
        {"Введите новый VIN здесь -> ",MSG_CMD_CON_CREATE_HELP},
        {"Неправильный синтаксис , <VID>\n",MSG_CMD_CON_CREATE_ERR},
        {"Таблица пуста!\n",MSG_CMD_DELETE_TEMPTY},
        {"VIN %s не найден : ( \n",MSG_CMD_DELETE_VNF},
        {"Элемент первый в таблице!\n",MSG_CMD_DELETE_EFT},
        {"VIN %s Удален! \n",MSG_CMD_DELETE_OK},
        {"VIN %s Удаление не выполнено , ошибка! \n",MSG_CMD_DELETE_ERR2},
        {"Удалить запись . Синтаксис <VIN> \n",MSG_CMD_DELETE_CON_HELP},
        {"Слишком много аргументов!",MSG_CMD_DELETE_CON_ERR},
        {"Неизвестный символ или вы не можете редактировать VIN \n",MSG_CMD_EDIT_ERR1},
        {"Нет записей! Нечего редактировать \n",MSG_CMD_EDIT_ERR1},
        {"Вы не ввели фильтр после слова BY \n",MSG_CMD_EDIT_ERR2},
        {"Мы редактируем только текущую строку! \n",MSG_CMD_EDIT_MSG1},
        {"Было ФИО : %s\n",MSG_CMD_EDIT_BF},
        {"Стало ФИО : %s\n OK! \n",MSG_CMD_EDIT_AF},
        {"Был Бренд : %s\n",MSG_CMD_EDIT_BB},
        {"Стал Бренд : %s\n OK! \n",MSG_CMD_EDIT_AB},
        {"Была Модель : %s\n",MSG_CMD_EDIT_BM},
        {"Стала Модель : %s\n OK! \n",MSG_CMD_EDIT_AM},
        {"Неизвестный символ или вы не можете редактировать VIN \n",MSG_CMD_EDIT_ERR3},
        {"Успех!\n",MSG_CMD_EDIT_OK},
        {"<Ошибка ввода> \n ",MSG_CMD_EDIT_CON_ERR},
        {"Редактировать элемент . Синтаксис <Новые данные> ; <Имя столбца>  by <столбец> <данные> \n ",MSG_CMD_EDIT_CON_HELP},
        {"Файл %s не найден \n",MSG_CMD_LOAD_FNF},
        {"Ошибка открытия файла! \n",MSG_CMD_LOAD_FOE},
        {"\n количество байтов : %i \n",MSG_CMD_LOAD_MSG1},
        {"Не могу открыть или создать %s файл",MSG_CMD_LOAD_ERRIO},
        {"ключ %s , ключ %s\n",MSG_CMD_LOAD_MSG2},
        {"\n Пароль [%s] не совпадает после расшифровки \n",MSG_CMD_LOAD_ERRPASS},
        {"Пароль OK!\n",MSG_CMD_LOAD_POK},
        {"Пароль без шифрования . Сравнение [%s] и [%s]\n",MSG_CMD_LOAD_PWE},
        {"Пароль [%s] Не соответствует после расшифровки, попробую другой метод ... \n",MSG_CMD_LOAD_PWEERR},
        {"Извините, не могу открыть. Пароль не соответствует \n",MSG_CMD_LOAD_PNM},
        {"Ошибка в строке <Полное имя>; <Бренд>; <Модель>; \n",MSG_CMD_LOAD_ERR1},
        {"Ошибка в строке <Бренд>; <Модель>; \n",MSG_CMD_LOAD_ERR2},
        {"Ошибка в строке <Модель> ; \n",MSG_CMD_LOAD_ERR3},
        {"Сканирование : [%s] [%s] \n",MSG_CMD_LOAD_S},
        {"Загрузка OK! Всего : %i записей \n",MSG_CMD_LOAD_OK},
        {"Ошибка ввода <имя файла> <ключ>\n",MSG_CMD_LOAD_EIP},
        {"Обнаружение зашифрованных файлов! Чтение данных ... Всего %i записей \n",MSG_CMD_LOAD_DE},
        {"Применение: %s key_file target_file output_file \n",MSG_CMD_LOAD_HELP},
        {"Хотите попробовать ввести пароль?! Y / N \n",MSG_CMD_LOAD_Q},
        {"Отмена... \n",MSG_CMD_LOAD_CANS},
        {"\n в s_loaded_file . Текущий ключ загружен [%s] \n",MSG_CMD_LOAD_MSG3},
        {"Не удается сохранить \'пустоту!\'\n",MSG_CMD_SAVE_ERR},
        {"Сохранение OK!\n",MSG_CMD_SAVE_OK},
        {"Не удается сохранить \'пустоту!\'\n",MSG_CMD_SAVE_ERR1},
        {"%i байтов : \n",MSG_CMD_SAVE_MSG1},
        {"Шифрование и сохранение OK! \n",MSG_CMD_SAVE_EOK},
        {"sz_user_key : %i шифрование : %i \n",MSG_CMD_SAVE_CON_MSG1},
        {"Неверный ввод <имя файла> <ключ> <encrypt> \n",MSG_CMD_SAVE_CON_ERR},
        {"Неверное имя файла . Разрешается A-z и 0-9 первые буквы \n",MSG_CMD_SAVE_CON_ERR2},
        {"Ошибка ввода \n",MSG_CMD_SEARCH_ERR1},
        {"Не введенное значение <тип> <данные>\n",MSG_CMD_SEARCH_ERR2},
        {"Не найдено : ( \n",MSG_CMD_SEARCH_ERR3},
        {"Тип <имя> где <колонка> <данные>\n",MSG_CMD_SEARCH_CON_HELP},
        {"Невозможно отсортировать один элемент ! \n",MSG_CMD_SORT_ERR1},
        {"Используем метод : %i, desc : %i \n",MSG_CMD_SORT_MSG1},
        {"-----------------------ПЕРЕД ИЗМЕНЕНИЕМ-------------------------\n",MSG_CMD_SORT_MSG2},
        {" \n Найти предыдущий элемент: [%s] == MIN : [%s]\n\n",MSG_CMD_SORT_MSG3},
        {"-----НОВАЯ ТАБЛИЦА-------%s-------;------ \n",MSG_CMD_SORT_MSG4},
        {"-------------Конец----------- \n",MSG_CMD_SORT_MSG5},
        {"Сортировка завершена! \n",MSG_CMD_SORT_OK},
        {"Сортировка по VIN по умолчанию . Ошибка, имя не введено \n",MSG_CMD_SORT_HELP},
        {"Сортировка по VIN по умолчанию. Ошибка, должно быть \"by\" только \n",MSG_CMD_SORT_HELP1},
        {"Сортировка по VIN по умолчанию \n",MSG_CMD_SORT_HELP2},
        {"Отладка отключена \n",MSG_CMD_STRUCT_TOOLS_DEBUG},
        {"Отладка включена \n",MSG_CMD_STRUCT_TOOLS_DEBUGON},
         {"Удалено из памяти : %i записей!\n",MSG_CMD_STRUCT_TOOLS_DESTRUCT},
         {"Начало логирования ... %s\n",MSG_CMD_UNIST_STALOG},
         {"Исползуем Logfile.log \n",MSG_CMD_UNIST_MSG},
        {"ВВЕДИТЕ НОВЫЙ VIN :",MSG_GUI_CREATE_MSG1},
        {"ОТМЕНЕНО!",MSG_GUI_CREATE_CANS},
        {"ВВЕДИТЕ ИМЯ :",MSG_GUI_CREATE_EFN},
        {"ВВЕДИТЕ МОДЕЛЬ :",MSG_GUI_CREATE_EM},
        {"ВВЕДИТЕ БРЕНД :",MSG_GUI_CREATE_EB},
        {"ВЫ ВВЕЛИ :",MSG_GUI_CREATE_MSG2},
        {"ВСЕ ХОРОШО? НАЖМИТЕ Y (ДА) / N (НЕТ)",MSG_GUI_CREATE_MSG3},
        {"СОЗДАНО!",MSG_GUI_CREATE_OK},
        {"СОЗДАТЬ ЗАПИСЬ",MSG_GUI_CREATE_MSG4},
        {"ХОТИТЕ ВЫЙТИ ? НАЖМИТЕ <-",MSG_GUI_CREATE_MSG5},
        {"НАЖ. ЛЮБ. КЛ. ДЛЯ ПРОДОЛЖЕНИЯ",MSG_GUI_CREATE_MSG6},
        {"РЕЖИМ ОТЛАДКИ ВЫКЛЮЧЕН \n",MSG_GUI_DEBUG_ON},
        {"РЕЖИМ ОТЛАДКИ ВКЛЮЧЕН \n",MSG_GUI_DEBUG_OFF},
        {"ХОТИТЕ ИЗМЕНИТЬ ИФО ? Y/N ",MSG_GUI_EDIT_EFN},
        {"->",MSG_GUI_EDIT_NFN},
        {"ИЗМЕНЕНО на '%s' !",MSG_GUI_EDIT_MSG1},
        {"ХОТИТЕ ИЗМЕНИТЬ МОДЕЛЬ? Y/N ",MSG_GUI_EDIT_EM},
        {"->",MSG_GUI_EDIT_NM},
        {"->",MSG_GUI_EDIT_NB},
        {"ХОТИТЕ ИЗМЕНИТЬ БРЕНД? Y / N",MSG_GUI_EDIT_NBB},
        {"ИЗМЕНИТЬ ЗАПИСЬ",MSG_GUI_EDIT_EE},
        {"ИНФО",MSG_GUI_HELPINFO_MSG1},
        {"СПРАВКА",MSG_GUI_HELPINFO_MSG2},
        {"Элемент удален успешно!",MSG_GUI_LIST_DEL},
        {"ТЕКУЩАЯ ЗАПИСЬ",MSG_GUI_LISTINFO_MSG1},
        {"ИМЯ : %s",MSG_GUI_LISTINFO_NAME},
        {"ФАМИЛИЯ : %s",MSG_GUI_LISTINFO_SUR},
        {"ОТЧЕСТВО : %s",MSG_GUI_LISTINFO_NAME2},
        {"БРЕНД: %s",MSG_GUI_LISTINFO_BRA},
        {"МОДЕЛЬ: %s",MSG_GUI_LISTINFO_MOD},
        {"СПИСОК",MSG_GUI_LISTINFO_LI},
        {"ОБОЗРЕВАТЕЛЬ",MSG_GUI_LOAD_MSG1},
        {"ЗАГРУЖЕНО %s OK! НАЖМИТЕ ENTER!",MSG_GUI_LOAD_MSG2},
        {"РАСШИРЕННАЯ ЗАГРУЗКА",MSG_GUI_LOAD_MSG3},
        {"ВЫБРАНО : '%s'!",MSG_GUI_LOAD_MSG4},
        {"ЗАГРУЗИТЬ ЭТОТ ФАЙЛ Y/N ?",MSG_GUI_LOAD_MSG5},
        {"ХОТИТЕ ВВЕСТИ ПАРОЛЬ Y/N ?",MSG_GUI_LOAD_MSG6},
        {"ВВЕДИТЕ ПАРОЛЬ: ",MSG_GUI_LOAD_MSG7},
        {"ОК . ЗАГРУЗКА ...",MSG_GUI_LOAD_MSG8},
        {"ОШИБКА :( НАЖМИТЕ ЛЮБУЮ КЛАВИШУ",MSG_GUI_LOAD_MSG9},
        {"УСПЕХ! НАЖМИТЕ ЛЮБУЮ КЛАВИШУ",MSG_GUI_LOAD_MSG10},
        {"Все записи удалены! Всего %i",MSG_GUI_RESET},
        {"Сохранено %s OK! НАЖ. ВВОД!",MSG_GUI_SAVE_MSG1},
        {"НЕЧЕГО СОХРАНЯТЬ! НАЖМИТЕ ВВОД!",MSG_GUI_SAVE_MSG2},
        {"ВВЕДИТЕ НОВОЕ ИМЯ : ",MSG_GUI_SAVE_MSG3},
        {"Отменен . НАЖМИТЕ ЛЮБУЮ КНОПКУ",MSG_GUI_SAVE_MSG4},
        {"ИМЯ ФАЙЛА :",MSG_GUI_SAVE_MSG5},
        {"%s ВСЕ OK ? Y/N ",MSG_GUI_SAVE_MSG6},
        {"СОХР. %s .НАЖ. ВВОД!",MSG_GUI_SAVE_MSG7},
        {"ВВЕДИТЕ НОВОЕ ИМЯ : ",MSG_GUI_SAVE_MSG8},
        {"ВВЕДИТЕ ПАРОЛЬ : ",MSG_GUI_SAVE_EP},
        {"СОХРАНИТЬ ? Y/N ",MSG_GUI_SAVE_SA},
        {"СОХРАНИТЬ КАК",MSG_GUI_SAVE_SAA},
        {"Сохранено %s OK!",MSG_GUI_SAVE_MSG9},
        {"ПОИСК ЗАПИСЕЙ",MSG_GUI_SEARCH_PRE},
        {"ВВОД %s : ",MSG_GUI_SEARCH_MSG1},
        {"[Бета]Найдено : [%i]",MSG_GUI_SEARCH_MSG2},
        {"Терминал не поддерживает цвета :( \n",MSG_GUI_SETT},
        {"Вы нажали = %3d Он может быть напечатан как '%c'",MSG_SYSMSG_MSG1},
        {"СОРТИРОВКА ЗАПИСЕЙ",MSG_SORT_MSG},
        {"Сортировка завершена!",MSG_SORT_OK},
        {"Отладка [choice_list=%i] , [i_count_l=%i] Название VIN = %s ",MSG_GUI_TOOLS_MSG1},
        {"Используйте клавиши вверх и вниз, Нажмите ввод , чтобы выбрать пункт . F10 или ESC - быстрый выход",MSG_GUI_MENU_MSG1},
        {"Панель скрыта!",MSG_GUI_MENU_HID},
        {"Панель включена!",MSG_GUI_MENU_SHOW},
        {"ГЛАВНОЕ МЕНЮ",MSG_GUI_MENU_MAIN},
        {"Нет записей!",MSG_GUI_MENU_NOENT},
        {"Используйте клавиши вверх и вниз. ВВОД, чтобы выбрать пункт. F10 - быстрый выход",MSG_GUI_MENU_MSG2},
        {"Вы выбрали %d , строка %s\n",MSG_GUI_MENU_MSG3},
        {"Добро пожаловать!\n",MSG_MENU_MSG},
        {"Меню>",MSG_MENU_MSG2},
        {"Аргумент не найден \n",MSG_MENU_MSG3},
        {"Всего : %i \n",MSG_MENU_MSG4},
        {"Неизвестная команда ... \n",MSG_MENU_MSG5},
        {"Пока !",MSG_MENU_MSG6}








    }

};

int change_lang(){ // функция смены языка программы
    LANG_MSG_BOX * current_lang = lbox[short_lang_data];
    if(current_lang == lbox[EN_EN]){
        current_lang = lbox[EN_RU];
        short_lang_data = EN_RU;
    }else{
        current_lang = lbox[EN_EN];
        short_lang_data = EN_EN;
    }
    return 0;
}

const char * pmsg(int id_msg){ // функция возвращает по ид строку перевода в определенном языке
    LANG_MSG_BOX * current_lang = lbox[short_lang_data];
    return current_lang[id_msg].msg_name;
}
